package com.gamespace.app.channels

import android.content.Context
import android.os.Environment
import io.flutter.plugin.common.MethodCall
import io.flutter.plugin.common.MethodChannel
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.launch
import java.io.File
import java.io.FileOutputStream
import java.util.zip.ZipEntry
import java.util.zip.ZipOutputStream

class MagiskExporterChannel(private val context: Context) : MethodChannel.MethodCallHandler {
    companion object {
        const val CHANNEL = "com.gamespace.app/magisk_exporter"
    }

    private val scope = CoroutineScope(Dispatchers.IO + SupervisorJob())

    override fun onMethodCall(call: MethodCall, result: MethodChannel.Result) {
        when (call.method) {
            "exportMagiskModule" -> {
                val tweaks = call.argument<Map<String, String>>("tweaks") ?: emptyMap()
                val moduleName = call.argument<String>("moduleName") ?: "GameSpace_Optimization"

                scope.launch {
                    val zipPath = createMagiskZip(moduleName, tweaks)
                    if (zipPath != null) {
                        result.success(zipPath)
                    } else {
                        result.error("EXPORT_FAILED", "Failed to generate Magisk zip", null)
                    }
                }
            }
            else -> result.notImplemented()
        }
    }

    private fun createMagiskZip(moduleName: String, tweaks: Map<String, String>): String? {
        return try {
            val downloadDir = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS)
            if (!downloadDir.exists()) downloadDir.mkdirs()

            val zipFile = File(downloadDir, "${moduleName}_Magisk.zip")
            val zos = ZipOutputStream(FileOutputStream(zipFile))

            // 1. module.prop
            val moduleProp = """
                id=gamespace_tweaks
                name=$moduleName
                version=v1.0.0
                versionCode=100
                author=GAME SPACE Pro
                description=System properties optimization module generated by Game Space Pro.
            """.trimIndent()
            addZipFile(zos, "module.prop", moduleProp.toByteArray())

            // 2. system.prop
            val sb = StringBuilder("# Game Space Pro Tweaks\n")
            for ((k, v) in tweaks) {
                sb.append("$k=$v\n")
            }
            addZipFile(zos, "system.prop", sb.toString().toByteArray())

            // 3. update-binary (Magisk script format)
            val updateBinary = """
                #!/sbin/sh
                OIFS=${'$'}IFS
                IFS='|'
                PATH=${'$'}PATH:/sbin
                umask 022
                exit 0
            """.trimIndent()
            addZipFile(zos, "META-INF/com/google/android/update-binary", updateBinary.toByteArray())

            val updaterScript = "# Magisk Module Installer\nui_print \"Installing Game Space Tweaks...\"\n"
            addZipFile(zos, "META-INF/com/google/android/updater-script", updaterScript.toByteArray())

            zos.close()
            zipFile.absolutePath
        } catch (e: Exception) {
            null
        }
    }

    private fun addZipFile(zos: ZipOutputStream, fileName: String, content: ByteArray) {
        val entry = ZipEntry(fileName)
        zos.putNextEntry(entry)
        zos.write(content)
        zos.closeEntry()
    }
}
