apply plugin: 'com.android.application'

android {
    namespace 'com.gamebooster.app'
    compileSdk 36

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    defaultConfig {
        applicationId "com.gamebooster.app"
        minSdk 24
        targetSdk 36
        versionCode 200
        versionName "2.0.0"
    }

    buildFeatures {
        aidl true
        buildConfig true
    }

    buildTypes {
        release {
            signingConfig signingConfigs.debug
            minifyEnabled false
            shrinkResources false
        }
    }
    applicationVariants.all { variant ->
        variant.outputs.all { output ->
            if (variant.buildType.name == 'debug') {
                outputFileName = "Game_Space_Debug.apk"
            } else {
                outputFileName = "Game_Space.apk"
            }
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.0'
    implementation 'androidx.lifecycle:lifecycle-viewmodel:2.8.7'
    implementation 'androidx.lifecycle:lifecycle-livedata:2.8.7'

    def shizuku_version = "13.1.5"
    implementation "dev.rikka.shizuku:api:${shizuku_version}"
    implementation "dev.rikka.shizuku:provider:${shizuku_version}"
    implementation 'com.github.bumptech.glide:glide:4.16.0'
}
